### ISSUE TITLE
StackIt Logo being looked for in the wrong directory

### ISSUE THREAD

**Issue by JeffHoogland** [poppu-mtg/StackIt#69]
Traceback (most recent call last):
  File "StackIt.py", line 9, in <module>
    import builder, config, GUIapp, watcher
  File "/media/Storage/GitHub/StackIt/GUIapp.py", line 88, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 2410, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: '/media/Storage/GitHub/HexAPIStreamingTools/StackIt/resources/StackIt-Logo.png'

The file appears to be located in StackIt/StackIt/resources not StackIt/resources

**Comment by JeffHoogland** [comment]
Also - I'm getting this error related to the GUI app when I am trying to run stackit from the command line. Why is that? If I'm running from the command line should it ignore the GUI aspect all together?

**Comment by silasary** [comment]
It should.  I think I messed that up while blindly following PEP8 recommendations.

As for the logo issue, I'll have a look into it.
