### ISSUE TITLE
New Issues - Traceback

### ISSUE THREAD

**Issue by FaiLucas** [poppu-mtg/StackIt#78]
Hi! I've been using the program for some months, but recently it seems to have a problem tracing cards I think. When tracing cards sometimes it stops because of an error, I'll copy it here if it helps. (Thank you and congratulations for the awesome program):

Exception in Tkinter callback
Traceback (most recent call last):
  File "site-packages\urllib3\connectionpool.py", line 601, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 346, in _make_request
  File "site-packages\urllib3\connectionpool.py", line 850, in _validate_conn
  File "site-packages\urllib3\connection.py", line 326, in connect
  File "site-packages\urllib3\util\ssl_.py", line 329, in ssl_wrap_socket
  File "ssl.py", line 377, in wrap_socket
  File "ssl.py", line 752, in __init__
  File "ssl.py", line 988, in do_handshake
  File "ssl.py", line 633, in do_handshake
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\requests\adapters.py", line 440, in send
  File "site-packages\urllib3\connectionpool.py", line 639, in urlopen
  File "site-packages\urllib3\util\retry.py", line 388, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='magiccards.info', port=443): Max retries exceeded with url: /mm2/en.html (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tkinter\__init__.py", line 1550, in __call__
  File "StackIt\GUIapp.py", line 57, in OpenPro1
  File "StackIt\builder.py", line 281, in main
  File "StackIt\decklist.py", line 102, in parse_list
  File "StackIt\scraper.py", line 155, in get_card_info
  File "StackIt\scraper.py", line 209, in get_json
  File "StackIt\scraper.py", line 32, in download_scan
  File "site-packages\requests\sessions.py", line 521, in get
  File "site-packages\requests\sessions.py", line 508, in request
  File "site-packages\requests\sessions.py", line 640, in send
  File "site-packages\requests\sessions.py", line 640, in <listcomp>
  File "site-packages\requests\sessions.py", line 218, in resolve_redirects
  File "site-packages\requests\sessions.py", line 618, in send
  File "site-packages\cachecontrol\adapter.py", line 50, in send
  File "site-packages\requests\adapters.py", line 506, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='magiccards.info', port=443): Max retries exceeded with url: /mm2/en.html (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)'),))

**Comment by silasary** [comment]
MagicCards.info appears to have let their SSL certificate expire.
![image](https://user-images.githubusercontent.com/194254/35715558-5bc21716-0827-11e8-81b8-b7957425276b.png)

We either need to switch to using Scryfall as our image provider, or wait for MCI to fix stuff on their side.
